name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12, 3.13]
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install uv pre-commit
          # Si nécessaire, installez aussi vos autres dépendances (ex.: pip install -r requirements.txt)

      - name: Vérification des outils (pre-commit)
        run: uv run pre-commit run -a

      - name: Exécution des tests
        run: uv run python -m unittest
